function reactClassNames(tailwind) {
  return tailwind
    ? {
        shell: 'min-h-screen bg-[#101114] text-slate-50',
        workspace: 'mx-auto flex min-h-screen w-[min(1240px,calc(100vw-2rem))] flex-col gap-4 py-6',
        topbar: 'flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-4',
        badge: 'inline-flex w-fit items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-black uppercase text-[#f5c451]',
        grid: 'grid flex-1 gap-4 lg:grid-cols-[260px_minmax(0,1fr)_320px]',
        panel: 'rounded-lg border border-white/10 bg-[#181a20]/95 p-5 shadow-2xl shadow-black/25',
        sidebar: 'rounded-lg border border-white/10 bg-[#14171d]/95 p-4',
        navItem: 'flex items-center justify-between rounded-md border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-slate-300',
        hero: 'rounded-lg border border-cyan-300/20 bg-[#1b1f27] p-5',
        statGrid: 'mt-4 grid gap-3 sm:grid-cols-3',
        stat: 'rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-slate-300',
        table: 'mt-4 overflow-hidden rounded-lg border border-white/10',
        row: 'grid gap-2 border-t border-white/10 px-4 py-3 first:border-t-0 sm:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]',
        button: 'inline-flex items-center justify-center gap-2 rounded-lg bg-cyan-300 px-4 py-3 font-black text-slate-950 transition hover:bg-[#f5c451] disabled:cursor-wait disabled:opacity-70',
        pre: 'mt-4 min-h-28 overflow-auto rounded-lg border border-white/10 bg-[#101114] p-4 text-sm text-cyan-100'
      }
    : {
        shell: 'app-shell',
        workspace: 'workspace',
        topbar: 'topbar',
        badge: 'badge',
        grid: 'dashboard-grid',
        panel: 'panel',
        sidebar: 'sidebar',
        navItem: 'nav-item',
        hero: 'hero-block',
        statGrid: 'stat-grid',
        stat: 'stat-card',
        table: 'work-table',
        row: 'work-row',
        button: 'primary-button',
        pre: 'response-box'
      };
}

function createReactAppTsx({ serverless = false, tailwind = false } = {}) {
  const cn = reactClassNames(tailwind);

  if (serverless) {
    return String.raw`import { useEffect, useState } from 'react';
import { Activity, CheckCircle2, Clock3, LayoutDashboard, Server, ShieldCheck } from 'lucide-react';
import { getServerlessMessage } from '../lib/services/serverlessService';
import '../styles/app.css';

type ApiState = {
  message: string;
  status: 'idle' | 'loading' | 'ready' | 'error';
};

const sprintItems = [
  ['API Gateway', 'Ready'],
  ['Function Deploy', 'Queued'],
  ['Security Review', 'Watching'],
  ['Scafkit Structure', 'Generated']
];

const scafkitCommands = [
  ['Create serverless', 'scafkit react app --serverless --tw'],
  ['Run locally', 'scafkit run'],
  ['Build', 'npm run build']
];

export default function App() {
  const [apiState, setApiState] = useState<ApiState>({
    message: 'Click the action to call your Netlify function.',
    status: 'idle'
  });

  async function loadServerlessMessage() {
    try {
      setApiState({ message: 'Calling serverless function...', status: 'loading' });
      const response = await getServerlessMessage();
      setApiState({ message: response.message, status: 'ready' });
    } catch (error) {
      setApiState({
        message: error instanceof Error ? error.message : 'Serverless function failed.',
        status: 'error'
      });
    }
  }

  useEffect(() => {
    document.title = 'Scafkit React Serverless Starter';
  }, []);

  return (
    <main className="${cn.shell}">
      <div className="${cn.workspace}">
        <header className="${cn.topbar}">
          <div>
            <span className="${cn.badge}"><ShieldCheck size={16} /> Production workspace</span>
            <h1>Serverless operations dashboard</h1>
          </div>
          <button className="${cn.button}" onClick={loadServerlessMessage} disabled={apiState.status === 'loading'}>
            <Server size={18} />
            Call function
          </button>
        </header>

        <section className="${cn.grid}">
          <aside className="${cn.sidebar}" aria-label="Workspace navigation">
            <strong>Workspace</strong>
            <span className="${cn.navItem}">Overview <LayoutDashboard size={16} /></span>
            <span className="${cn.navItem}">Security <ShieldCheck size={16} /></span>
            <span className="${cn.navItem}">Activity <Activity size={16} /></span>
            <span className="${cn.navItem}">Generated by Scafkit <CheckCircle2 size={16} /></span>
          </aside>

          <section className="${cn.panel}">
            <div className="${cn.hero}">
              <span className="${cn.badge}"><Clock3 size={16} /> Scafkit CLI starter</span>
              <h2>Ship from a production-shaped React surface.</h2>
              <p>Scafkit is an interactive CLI for generating starter projects. This serverless React starter includes app, feature, service, API, config, and Netlify function boundaries from the first commit.</p>
            </div>
            <div className="${cn.statGrid}">
              <span className="${cn.stat}"><strong>4</strong> tracked streams</span>
              <span className="${cn.stat}"><strong>99.9%</strong> target uptime</span>
              <span className="${cn.stat}"><strong>1</strong> function endpoint</span>
            </div>
            <div className="${cn.table}">
              {sprintItems.map(([name, status]) => (
                <div className="${cn.row}" key={name}>
                  <span>{name}</span>
                  <strong>{status}</strong>
                </div>
              ))}
            </div>
            <pre className="${cn.pre}">{apiState.message}</pre>
          </section>

          <aside className="${cn.panel}">
            <CheckCircle2 size={28} />
            <h2>Scafkit command deck</h2>
            <p>Generate focused starters, add Tailwind with --tw, skip installs with --no-install, and keep the first screen ready for real product work.</p>
            <div className="${cn.table}">
              {scafkitCommands.map(([label, command]) => (
                <div className="${cn.row}" key={label}>
                  <span>{label}</span>
                  <strong>{command}</strong>
                </div>
              ))}
            </div>
          </aside>
        </section>
      </div>
    </main>
  );
}
`;
  }

  return String.raw`import { useMemo, useState } from 'react';
import { Activity, Boxes, CheckCircle2, LayoutDashboard, ShieldCheck, Workflow } from 'lucide-react';
import { createRequestClient } from '../lib/api/requestClient';
import { createStorageService } from '../lib/services/storageService';
import '../styles/app.css';

const workItems = [
  ['Application shell', 'Generated'],
  ['Service layer', 'Ready'],
  ['API client', 'Configured'],
  ['Scafkit Structure', 'Active']
];

const scafkitCommands = [
  ['Create React', 'scafkit react app --tw'],
  ['Serverless', 'scafkit react app --serverless'],
  ['Run locally', 'scafkit run']
];

export default function App() {
  const requestClient = useMemo(() => createRequestClient({ baseUrl: import.meta.env.VITE_API_URL || '' }), []);
  const storageService = useMemo(() => createStorageService(), []);
  const [result, setResult] = useState('No action yet.');

  function runClientDemo() {
    storageService.set('scafkit-demo', 'Client-side service is working.');
    const saved = storageService.get('scafkit-demo');
    const endpoint = requestClient.buildUrl('/api/example');
    setResult('Saved: ' + saved + '\nEndpoint: ' + endpoint);
  }

  return (
    <main className="${cn.shell}">
      <div className="${cn.workspace}">
        <header className="${cn.topbar}">
          <div>
            <span className="${cn.badge}"><ShieldCheck size={16} /> Scafkit React starter</span>
            <h1>Product launch workspace</h1>
          </div>
          <button className="${cn.button}" onClick={runClientDemo}>
            <Workflow size={18} />
            Run client demo
          </button>
        </header>

        <section className="${cn.grid}">
          <aside className="${cn.sidebar}" aria-label="Workspace navigation">
            <strong>Workspace</strong>
            <span className="${cn.navItem}">Overview <LayoutDashboard size={16} /></span>
            <span className="${cn.navItem}">Pipeline <Activity size={16} /></span>
            <span className="${cn.navItem}">Quality <CheckCircle2 size={16} /></span>
            <span className="${cn.navItem}">Generated by Scafkit <ShieldCheck size={16} /></span>
          </aside>

          <section className="${cn.panel}">
            <div className="${cn.hero}">
              <span className="${cn.badge}"><Boxes size={16} /> Production React surface</span>
              <h2>Start with a real workspace instead of a blank demo.</h2>
              <p>Scafkit is an interactive CLI for generating starter projects. This React starter gives you app, feature, service, API, config, adapter, and utility folders with a production-minded launch workspace.</p>
            </div>
            <div className="${cn.statGrid}">
              <span className="${cn.stat}"><strong>8</strong> source zones</span>
              <span className="${cn.stat}"><strong>4</strong> work items</span>
              <span className="${cn.stat}"><strong>0</strong> logo assets</span>
            </div>
            <div className="${cn.table}">
              {workItems.map(([name, status]) => (
                <div className="${cn.row}" key={name}>
                  <span>{name}</span>
                  <strong>{status}</strong>
                </div>
              ))}
            </div>
            <pre className="${cn.pre}">{result}</pre>
          </section>

          <aside className="${cn.panel}">
            <CheckCircle2 size={28} />
            <h2>Scafkit command deck</h2>
            <p>Create CSS or Tailwind React apps, add Netlify Functions, and run the generated workspace from the CLI.</p>
            <div className="${cn.table}">
              {scafkitCommands.map(([label, command]) => (
                <div className="${cn.row}" key={label}>
                  <span>{label}</span>
                  <strong>{command}</strong>
                </div>
              ))}
            </div>
          </aside>
        </section>
      </div>
    </main>
  );
}
`;
}

function createReactAppJsx(options) {
  return createReactAppTsx(options)
    .replace("type ApiState = {\n  message: string;\n  status: 'idle' | 'loading' | 'ready' | 'error';\n};\n\n", '')
    .replace('useState<ApiState>({', 'useState({');
}

function createReactStyles(tailwind = false) {
  if (tailwind) {
    return String.raw`@import "tailwindcss";

@layer base {
  :root {
    font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }

  * {
    box-sizing: border-box;
  }

  body {
    margin: 0;
    min-width: 320px;
    background: #101114;
  }

  h1 {
    margin: 0.5rem 0 0;
    font-size: clamp(2rem, 5vw, 4.25rem);
    line-height: 1;
  }

  h2 {
    margin: 1rem 0 0.5rem;
    font-size: clamp(1.35rem, 3vw, 2.2rem);
  }

  p {
    color: #b6bfcc;
    line-height: 1.75;
  }
}
`;
  }

  return String.raw`:root {
  color: #eff6ff;
  background: #101114;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --line: rgba(226, 232, 240, 0.14);
  --muted: #b6bfcc;
  --cyan: #2dd4bf;
  --blue: #60a5fa;
  --gold: #f5c451;
  --panel: rgba(24, 26, 32, 0.96);
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-width: 320px;
}

button {
  font: inherit;
}

.app-shell {
  min-height: 100vh;
  color: #eff6ff;
  background:
    linear-gradient(120deg, rgba(45, 212, 191, 0.14), transparent 34rem),
    linear-gradient(300deg, rgba(96, 165, 250, 0.12), transparent 30rem),
    linear-gradient(135deg, #101114 0%, #17191f 52%, #1d1a24 100%);
}

.workspace {
  width: min(1240px, calc(100vw - 2rem));
  min-height: 100vh;
  margin: 0 auto;
  padding: 1.5rem 0;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.topbar {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  align-items: center;
  border-bottom: 1px solid var(--line);
  padding-bottom: 1rem;
}

.topbar h1,
.hero-block h2 {
  margin: 0.5rem 0 0;
  line-height: 1;
}

.topbar h1 {
  font-size: clamp(2rem, 5vw, 4.25rem);
}

.dashboard-grid {
  display: grid;
  flex: 1;
  grid-template-columns: 260px minmax(0, 1fr) 320px;
  gap: 1rem;
}

.panel,
.sidebar,
.hero-block {
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
  box-shadow: 0 24px 90px rgba(0, 0, 0, 0.25);
}

.panel,
.hero-block {
  padding: 1.25rem;
}

.sidebar {
  padding: 1rem;
  display: grid;
  align-content: start;
  gap: 0.75rem;
}

.badge,
.primary-button,
.nav-item {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
}

.badge {
  width: fit-content;
  border: 1px solid rgba(45, 212, 191, 0.24);
  border-radius: 999px;
  padding: 0.35rem 0.7rem;
  background: rgba(45, 212, 191, 0.1);
  color: var(--gold);
  font-size: 0.74rem;
  font-weight: 900;
  text-transform: uppercase;
}

.nav-item,
.stat-card,
.work-table {
  border: 1px solid var(--line);
  background: rgba(255, 255, 255, 0.03);
}

.nav-item {
  justify-content: space-between;
  border-radius: 6px;
  padding: 0.7rem 0.8rem;
  color: var(--muted);
}

.hero-block {
  background: #1b1f27;
}

p {
  color: var(--muted);
  line-height: 1.75;
}

.stat-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 0.75rem;
  margin-top: 1rem;
}

.stat-card {
  border-radius: 8px;
  padding: 0.85rem;
  color: var(--muted);
}

.stat-card strong {
  display: block;
  color: #eff6ff;
}

.work-table {
  overflow: hidden;
  border-radius: 8px;
  margin-top: 1rem;
}

.work-row {
  display: grid;
  grid-template-columns: minmax(0, 0.8fr) minmax(0, 1.2fr);
  gap: 0.75rem;
  padding: 0.85rem 1rem;
  border-top: 1px solid var(--line);
}

.work-row:first-child {
  border-top: 0;
}

.work-row strong {
  color: var(--gold);
  overflow-wrap: anywhere;
}

.primary-button {
  justify-content: center;
  border: 0;
  border-radius: 8px;
  padding: 0.85rem 1rem;
  background: linear-gradient(135deg, var(--cyan), var(--blue));
  color: #06111f;
  font-weight: 900;
  cursor: pointer;
}

.primary-button:disabled {
  cursor: wait;
  opacity: 0.7;
}

.response-box {
  width: 100%;
  min-height: 112px;
  margin: 1rem 0 0;
  padding: 1rem;
  overflow: auto;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: #101114;
  color: #cffafe;
}

@media (max-width: 980px) {
  .dashboard-grid {
    grid-template-columns: 1fr;
  }

  .topbar {
    align-items: flex-start;
    flex-direction: column;
  }
}

@media (max-width: 680px) {
  .stat-grid {
    grid-template-columns: 1fr;
  }

  .work-row {
    grid-template-columns: 1fr;
  }
}
`;
}

module.exports = {
  createReactAppJsx,
  createReactAppTsx,
  createReactStyles,
};
